# ================================================================
# theme: dove
# ================================================================

title         : Dove
description   : A theme development project.
# title       : The title of your site
# description : Short description of your site.
author        : Techie Joe

version       : 0.1.0
revision      : 2602.2

baseurl       : /dove
home_url      : /dove
live_url      : https://techie-joe.github.io/dove

lang          : en-US

ghost: bG9jYWxob3N0OjQwMDAsdGVjaGllLWpvZS5naXRodWIuaW8
# ghost: your-tracking-id
# to track your ThemeJs.

# google_analytics: your-tracking-id
# to track your website using Google Analytics.

# cloudflare_analytics: your-tracking-id
# to track your website using Cloudflare Analytics.

# show_downloads: true
# true or false (unquoted).
# to indicate whether to provide a download URL.

# github:
#   zip_url: http://example.com/download.zip
#   another_url: another_value

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  # - jekyll-paginate
  # - jekyll-redirect-from
  # - jekyll-sitemap
  # - jekyll-feed
  # - jemoji

# exclude these from production (_site).
exclude:
  - ".editorconfig"
  - ".github"
  - ".gitignore"
  - ".sass-cache"
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - ".bundle"
  - "*.gem"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - script
  - vendor
  - node_modules
  - gulpfile.js
  - package-lock.json
  - package.json
  - CNAME
  - "*.x"
  - "*.ignore"
  - "*.backup"
  - "*.localhost"